#### Zachary Griffin   
Data 101   Spring 2026   Zare

# Project 2: Disease

### Introduction
My dataset is the US Contagious Diseases dataset originally from the Tycho project. It reports yearly counts of Hepatitis A, Measles, Mumps, Pertussis (whooping cough), Polio, Rubella, and Smallpox for all 50 states and DC. My interest lay in whooping cough, as a few years ago one of my choir mate's grandchildren caught the disease, which I had thought was eradicated. I am comparing whooping cough (pertussis) proportions in the DMV before and after the vhole-cell diptheia, tetanus, and pertussis (DTP) vaccine as released in 1948. Technically, this was the second whooping cough vaccine, but it was more successful than the original stand alone vaccine. 

### Data Analysis and Statistical Inference 
I filtered for just pertussis and the years 1947 and '48 (before and after the DTP vaccine was released), as well as for states District of Columbia, Maryland, and Virginia. I then summed cases and population for the two years. I then ran the difference of two proportion test. The null hypothesis was that there would be no difference between proportions of whooping cough cases in the DMV before and after the DTP vaccine. THe alternative hypthesis is that there is a difference in proportions between whooping cough cases in the DMV before and after the vaccine. I am using a significance value of 0.05. I was going to do the whole US but I was concerned about my number of observations being way too high-- not that they aren't still extremely high for just the DMV. 

### Conclusion and Future Directions

My result was a p-value of 0.00: to reject the null conclusion, there is a difference in proportions of whooping cough cases before and after the DTP vaccine. However, when I was setting up this test, I didn't consider about how sample size changes effect size, and the entire population of the DMV is my sample size. My number of obversations is *way* to huge, and would lead to rejecting the null hypothesis even if there was not a meaningful difference between the proportions. 
Originally, my future directions woud have been to see how the the proportions for whooping cough were across each region, and if they changed as the acellular vaccine DTaP was released the 1990s,  or as the booster Tdap was recommedned for teens in the 2006 (Mayo Clinic). However, any of those would have still had the same effect size problem and I'm not sure how to fix that with this data set. 

### References

https://www.mayoclinic.org/diseases-conditions/history-disease-outbreaks-vaccine-timeline/whooping-cough

## Analysis

In [15]:
# Load libraries and data set
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.stats.proportion import proportion_confint, proportions_ztest, proportion_effectsize
from scipy import stats
from statsmodels.stats.power import NormalIndPower, TTestIndPower, TTestPower
df = pd.read_csv("contagious_disease.csv")

In [7]:
# use info and head to get a sense of the data set
df.head()

       disease    state  year  weeks_reporting  count  population
0  Hepatitis A  Alabama  1966               50    321   3345787.0
1  Hepatitis A  Alabama  1967               49    291   3364130.0
2  Hepatitis A  Alabama  1968               52    314   3386068.0
3  Hepatitis A  Alabama  1969               49    380   3412450.0
4  Hepatitis A  Alabama  1970               51    413   3444165.0

In [22]:
# Filter for just pertussis (whooping cough) 
wc = df[(df['disease'] == 'Pertussis')]

# filter in the years 1947, 48, 
filter_years = [1947, 1948]

wc2 = wc[wc['year'].isin(filter_years)]

# filter for state is District of Columbia, Maryland or Virginia
filter_state = ['District Of Columbia', 'Maryland', 'Virginia']

wc3 = wc2[wc2['state'].isin(filter_state)]

wc3

,disease,state,year,weeks_reporting,count,population
8413,Pertussis,District Of Columbia,1947,51,606,781634.0
8414,Pertussis,District Of Columbia,1948,44,235,791123.0
9085,Pertussis,Maryland,1947,51,3886,2151667.0
9086,Pertussis,Maryland,1948,52,1031,2213121.0
10541,Pertussis,Virginia,1947,51,4066,3104896.0
10542,Pertussis,Virginia,1948,52,2244,3176279.0

In [23]:
# Group by year and sum total cases of Whooping cough and US population
wc_counts = wc3.groupby('year')[['count','population']].sum()

wc_counts

      count  population
year
1947   8558   6038197.0
1948   3510   6180523.0

### Difference Two Proportion Test: 
Ho: The proportion of whooping cough cases in the DMV before and after the DTP vaccine are equal.

Ha: The proportion of whooping cough cases in the DMV before and after the DPT vaccine are not equal.

In [24]:
# set up variables 

#counts = ([wc_counts.at[1947, 'count'], [wc_counts.at[1948, 'count']]]) 
#nobs = ([wc_counts.at[1947, 'population'], [wc_counts.at[1948, 'population']]])
# I get errors about array size that I don't really understand when I try to access the counts and nobs from my table from the proportions test code,
# but it works fine when I manually type in the numbers 
counts = np.array([8558, 6038197])
nobs = np.array([3510, 6180523])

# run the difference of two proportion test
stat, pval = proportions_ztest(counts, nobs)
print(f"Z-statistic: {stat:.3f}, p-value: {pval:.4f}\n")

# interperet
if pval < 0.05:
    print("Reject Ho: Whooping cough proportions were different in the DMV before and after the DPT vaccine. ")
else:
    print("Fail to reject H0: no evidence that whooping cough proportions were different in the DMV before and after the DPT vaccine.")

Z-statistic: 587.424, p-value: 0.0000

Reject Ho: Whooping cough proportions were different in the US before and after the DPT vaccine.